/**
 * Friendly labels for agent tool names shown in the UI.
 * Tools mapped to `null` are internal/diagnostic and should be hidden.
 */
export const TOOL_LABELS: Record<string, string | null> = {
  // Diagnostic/internal — hide from user
  check_tenant_readiness: null,
  list_memories: null,
  recall_accounting_preference: null,
  recall: null,
  suggest_next_configuration_step: null,
  explain_module_requirements: null,
  get_full_app_state: null,
  diagnose_config: null,
  scan_proactive_insights: null,
  search_knowledge: null,
  get_knowledge: null,
  how_to: null,
  audit_permissions: null,
  list_all_memories: null,
  forget: null,

  // Read tools
  read_company_setup: "Configuración",
  read_expense_policy: "Política de gastos",
  read_accounting_setup: "Contabilidad",
  read_accounting_setup_detailed: "Contabilidad detallada",
  list_legal_entities: "Entidades legales",
  list_users: "Usuarios",
  list_roles: "Roles",
  list_accounting_categories: "Categorías",
  list_categories_detail: "Categorías detalladas",
  list_pending_approvals: "Aprobaciones",
  list_vendors: "Proveedores",
  list_fiscal_deadlines: "Fechas SAT",
  list_ai_policies: "Políticas IA",
  list_projects: "Proyectos",
  list_clients: "Clientes",
  list_cost_centers: "Centros de costo",
  list_dimensions: "Dimensiones",
  list_chart_of_accounts_detailed: "Catálogo de cuentas",
  list_expense_reports: "Reportes",
  list_subcontractors: "Subcontratistas",
  list_time_projects: "Proyectos (tiempos)",
  list_user_roles: "Roles de usuario",
  list_permissions: "Permisos",
  list_role_permissions: "Permisos del rol",
  list_accounting_rules: "Reglas contables",
  accounting_health_check: "Salud contable",
  check_reimbursement_status: "Reembolso",
  get_current_period: "Período fiscal",
  get_accounting_dashboard: "Dashboard contable",
  explain_change_impact: "Impacto del cambio",
  expense_counts_by_status: "Conteo de gastos",
  expense_trends: "Tendencias",
  spend_summary: "Resumen gastos",
  spend_by_project: "Gastos por proyecto",
  top_vendors: "Top proveedores",
  budget_vs_actual: "Presupuesto vs real",
  time_allocation_summary: "Resumen tiempos",
  time_report_summary: "Reporte de tiempos",
  search_expenses: "Buscar gastos",
  search_users: "Buscar usuarios",
  search_projects: "Buscar proyectos",
  get_sat_reference: "Referencia SAT",
  is_period_locked: "Período bloqueado",
  get_current_config: "Configuración actual",
  get_company_config: "Config empresa",
  read_channel_settings: "Canales",
  read_auth_settings: "Autenticación",
  read_storage_config: "Almacenamiento",
  read_archive_config: "Archivo",
  read_report_cycle: "Ciclo de reportes",
  read_export_bundle_config: "Config exportación",
  trace_workflow: "Flujo de aprobación",
  expense_validation: "Validación de gastos",
  review_queue: "Cola de revisión",
  my_week_summary: "Resumen semanal",
  cached_currency_convert: "Conversión moneda",
  exchange_rate: "Tipo de cambio",
  calculate_retentions: "Retenciones",
  convert_currency: "Convertir moneda",
  get_cached_exchange_rate: "Tipo de cambio",

  // Write tools
  create_expense: "Crear gasto",
  create_expense_from_receipt: "Gasto desde recibo",
  approve_expense: "Aprobar",
  reject_expense: "Rechazar",
  quick_approve: "Aprobar rápido",
  quick_reject: "Rechazar rápido",
  submit_expense: "Enviar gasto",
  create_legal_entity: "Crear entidad",
  create_dimension: "Crear dimensión",
  create_vendor: "Crear proveedor",
  create_accounting_rule: "Crear regla",
  create_ai_policy: "Crear política IA",
  create_accounting_category: "Crear categoría",
  create_cost_center_hierarchy: "Crear centro de costo",
  create_role_from_template: "Crear rol",
  create_user: "Crear usuario",
  create_subcontractor: "Crear subcontratista",
  create_tax_rate: "Crear tasa de impuesto",
  create_approval_chain: "Crear cadena de aprobación",
  save_accounting_preference: "Guardar preferencia",
  remember: "Memorizar",
  update_company_setup: "Actualizar empresa",
  update_expense_policy: "Actualizar política",
  update_accounting_setup: "Actualizar contabilidad",
  update_accounting_setup_full: "Actualizar contabilidad (completo)",
  update_channel_settings: "Actualizar canales",
  update_auth_settings: "Actualizar autenticación",
  update_storage_config: "Actualizar almacenamiento",
  update_archive_config: "Actualizar archivo",
  update_report_cycle: "Actualizar ciclo",
  update_export_bundle_config: "Actualizar exportación",
  update_company_policy: "Actualizar política",
  update_platform_mailbox: "Actualizar buzón",
  update_user: "Actualizar usuario",
  update_user_permissions: "Actualizar permisos",
  update_ai_policy: "Actualizar política IA",
  update_policy: "Actualizar política",
  update_workflow: "Actualizar flujo",
  delete_accounting_rule: "Eliminar regla",
  delete_ai_policy: "Eliminar política IA",
  delete_workflow_transition: "Eliminar transición",
  toggle_ai_policy: "Activar/desactivar política IA",
  deactivate_user: "Desactivar usuario",
  reactivate_user: "Reactivar usuario",
  assign_user_role: "Asignar rol",
  revoke_user_role: "Revocar rol",
  grant_role_permission: "Conceder permiso",
  revoke_role_permission: "Revocar permiso",
  invite_user: "Invitar usuario",
  send_announcement: "Enviar anuncio",
  configure_notifications: "Configurar notificaciones",
  upsert_legal_entity: "Actualizar entidad",
  upsert_client: "Actualizar cliente",
  upsert_cost_center: "Actualizar centro de costo",
  upsert_project: "Actualizar proyecto",
  upsert_workflow_stage: "Actualizar etapa",
  upsert_workflow_transition: "Actualizar transición",
  clone_workflow: "Clonar flujo",
  close_accounting_period: "Cerrar período",
  ingest_user_roster: "Importar usuarios",
  ingest_org_entities: "Importar datos",
  ingest_accounting_catalog: "Importar catálogo",
  ingest_file: "Analizar archivo",
  analyze_file: "Analizar archivo",

  // Finance copilot
  match_cfdis_batch: "Emparejar CFDIs",
  cfdi_mass_check: "Verificar CFDIs",
  cfdi_pair: "Emparejar CFDI",
  generate_poliza_preview: "Vista previa póliza",
  poliza_preview: "Vista previa póliza",
  preview_poliza: "Vista previa póliza",
  auto_categorize_expenses: "Categorizar gastos",
  detect_anomalies: "Detectar anomalías",
  find_missing_receipts: "Buscar recibos faltantes",
  pre_close_checklist: "Checklist cierre",
  run_month_end: "Cierre mensual",
  month_close: "Cierre mensual",
  build_expense_reports: "Generar reportes",
  review_expense_report: "Revisar reporte",
  resolve_report_issue: "Resolver problema",
  map_category_to_accounts: "Mapear categoría",
  map_sat_account: "Mapear cuenta SAT",
  match_accounting_rules: "Aplicar reglas",
  apply_accounting_preset: "Aplicar preset",
  bulk_create_accounting_categories: "Crear categorías (lote)",
  bulk_update_expenses: "Actualizar gastos (lote)",
  bundle_expenses: "Agrupar gastos",
  submit_time_entry: "Registrar tiempo",
  submit_time_week: "Registrar semana",
  test_platform_mailbox: "Probar buzón",
};

/**
 * Get a friendly label for a tool name, or fall back to the raw name.
 * Returns `null` if the tool should be hidden from the user.
 */
export function toolLabel(toolName: string): string | null {
  if (toolName in TOOL_LABELS) return TOOL_LABELS[toolName];
  // Unknown tools: show them with a friendly prefix
  return toolName.replace(/_/g, " ");
}

/**
 * Check if a tool call should be hidden from the user.
 */
export function isHiddenTool(toolName: string): boolean {
  return toolName in TOOL_LABELS && TOOL_LABELS[toolName] === null;
}
