"""add_request_no_to_purchase_requests

Revision ID: 4cc583b92709
Revises: d5e1f8a2b3c4
Create Date: 2026-04-20 13:25:44.664293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4cc583b92709'
down_revision: Union[str, Sequence[str], None] = 'd5e1f8a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add request_no column — global per-company PR number in format PR-YYYY-NNNNN."""
    op.add_column(
        'purchase_requests',
        sa.Column('request_no', sa.String(20), nullable=True),
    )
    op.create_unique_constraint('uq_purchase_requests_request_no', 'purchase_requests', ['request_no'])
    op.create_index('ix_purchase_requests_request_no', 'purchase_requests', ['request_no'])

    # Backfill existing rows: PR-{created_year}-{id:05d}  (safe one-time patch)
    op.execute("""
        UPDATE purchase_requests
        SET request_no = 'PR-' || TO_CHAR(created_at, 'YYYY') || '-' || LPAD(CAST(id AS TEXT), 5, '0')
        WHERE request_no IS NULL
    """)


def downgrade() -> None:
    op.drop_index('ix_purchase_requests_request_no', table_name='purchase_requests')
    op.drop_constraint('uq_purchase_requests_request_no', 'purchase_requests', type_='unique')
    op.drop_column('purchase_requests', 'request_no')

    op.drop_index(op.f('ix_pr_requester'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_company_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_requester_id'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_table('channel_verifications')
    op.drop_index(op.f('ix_time_entries_company_user'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_entry_date'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_project'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_week_start'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_channel_settings_company_id'), table_name='channel_settings')
    op.drop_table('channel_settings')
    op.drop_index(op.f('ix_time_activities_company'), table_name='time_activities')
    op.drop_table('time_activities')
    op.execute("DROP INDEX IF EXISTS ix_export_configs_company_id")
    op.execute("DROP TABLE IF EXISTS export_configs")
    op.drop_index(op.f('ix_company_auth_settings_company_id'), table_name='company_auth_settings')
    op.drop_table('company_auth_settings')
    op.drop_index(op.f('ix_time_assignments_project'), table_name='time_assignments')
    op.drop_index(op.f('ix_time_assignments_user'), table_name='time_assignments')
    op.drop_table('time_assignments')
    op.execute("DROP INDEX IF EXISTS ix_expense_tags_company_id")
    op.execute("DROP TABLE IF EXISTS expense_tags")
    op.drop_index(op.f('ix_request_attachments_company_id'), table_name='request_attachments')
    op.drop_index(op.f('ix_request_attachments_request_id'), table_name='request_attachments')
    op.drop_table('request_attachments')
    op.drop_index(op.f('ix_user_project_assignments_project_id'), table_name='user_project_assignments')
    op.drop_index(op.f('ix_user_project_assignments_user_id'), table_name='user_project_assignments')
    op.drop_table('user_project_assignments')
    op.drop_index(op.f('ix_time_projects_company'), table_name='time_projects')
    op.drop_table('time_projects')
    op.drop_index(op.f('ix_channel_conversations_company_id'), table_name='channel_conversations')
    op.drop_index(op.f('ix_channel_conversations_thread_id'), table_name='channel_conversations')
    op.drop_table('channel_conversations')
    op.drop_index(op.f('ix_channel_messages_company_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_thread_id'), table_name='channel_messages')
    op.drop_table('channel_messages')
    op.create_unique_constraint(None, 'users', ['whatsapp_phone'])
    op.create_foreign_key(None, 'users', 'users', ['delegates_for_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('channel_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('sender_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('wa_message_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachments_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('intent', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('error_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('channel_messages_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_messages_pkey'))
    )
    op.create_index(op.f('ix_channel_messages_thread_id'), 'channel_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_company_id'), 'channel_messages', ['company_id'], unique=False)
    op.create_table('channel_conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sender_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('channel_conversations_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_conversations_pkey'))
    )
    op.create_index(op.f('ix_channel_conversations_thread_id'), 'channel_conversations', ['thread_id'], unique=False)
    op.create_index(op.f('ix_channel_conversations_company_id'), 'channel_conversations', ['company_id'], unique=False)
    op.create_table('time_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cost_center', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('discipline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('budget_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'completed'::character varying, 'on_hold'::character varying]::text[])", name=op.f('ck_time_project_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_projects_pkey'))
    )
    op.create_index(op.f('ix_time_projects_company'), 'time_projects', ['company_id'], unique=False)
    op.create_table('user_project_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('user_project_assignments_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_project_assignments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_project_assignments_pkey'))
    )
    op.create_index(op.f('ix_user_project_assignments_user_id'), 'user_project_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_project_assignments_project_id'), 'user_project_assignments', ['project_id'], unique=False)
    op.create_table('request_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attachment_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stored_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("attachment_type::text = ANY (ARRAY['file'::character varying, 'url'::character varying]::text[])", name=op.f('ck_request_attachment_type_valid')),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_requests.id'], name=op.f('request_attachments_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('request_attachments_pkey'))
    )
    op.create_index(op.f('ix_request_attachments_request_id'), 'request_attachments', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_attachments_company_id'), 'request_attachments', ['company_id'], unique=False)
    op.create_table('expense_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('expense_tags_pkey'))
    )
    op.create_index(op.f('ix_expense_tags_company_id'), 'expense_tags', ['company_id'], unique=False)
    op.create_table('time_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('budget_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['team_member'::character varying, 'lead'::character varying, 'coordinator'::character varying]::text[])", name=op.f('ck_time_assignment_role_valid')),
    sa.ForeignKeyConstraint(['project_id'], ['time_projects.id'], name=op.f('time_assignments_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('time_assignments_pkey')),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_time_assignment_project_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_time_assignments_user'), 'time_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_time_assignments_project'), 'time_assignments', ['project_id'], unique=False)
    op.create_table('company_auth_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('magic_link_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('allowed_email_domains', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sso_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sso_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sso_metadata_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('session_timeout_hours', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=False),
    sa.Column('require_mfa', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('company_auth_settings_pkey'))
    )
    op.create_index(op.f('ix_company_auth_settings_company_id'), 'company_auth_settings', ['company_id'], unique=True)
    op.create_table('export_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_pattern', sa.VARCHAR(length=255), server_default=sa.text("'{company}_{date}_{batch_id}.csv'::character varying"), autoincrement=False, nullable=False),
    sa.Column('folder_pattern', sa.VARCHAR(length=255), server_default=sa.text("'{year}/{month}/'::character varying"), autoincrement=False, nullable=False),
    sa.Column('export_format', sa.VARCHAR(length=10), server_default=sa.text("'csv'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_format', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('export_configs_pkey'))
    )
    op.create_index(op.f('ix_export_configs_company_id'), 'export_configs', ['company_id'], unique=False)
    op.create_table('time_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('time_activities_pkey'))
    )
    op.create_index(op.f('ix_time_activities_company'), 'time_activities', ['company_id'], unique=False)
    op.create_table('channel_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('wa_phone_number_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('wa_waba_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('wa_access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wa_webhook_verify_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('wa_display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email_inbound_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_webhook_secret', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('email_smtp_host', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_smtp_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email_smtp_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_smtp_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_smtp_from', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_settings_pkey')),
    sa.UniqueConstraint('company_id', 'channel', name=op.f('uq_channel_settings_company_channel'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_channel_settings_company_id'), 'channel_settings', ['company_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reviewer_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['draft'::character varying, 'submitted'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])", name=op.f('ck_time_entry_status_valid')),
    sa.CheckConstraint('hours > 0::numeric AND hours <= 24::numeric', name=op.f('ck_time_entry_hours_range')),
    sa.ForeignKeyConstraint(['activity_id'], ['time_activities.id'], name=op.f('time_entries_activity_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['time_projects.id'], name=op.f('time_entries_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('time_entries_pkey'))
    )
    op.create_index(op.f('ix_time_entries_week_start'), 'time_entries', ['week_start'], unique=False)
    op.create_index(op.f('ix_time_entries_project'), 'time_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_time_entries_entry_date'), 'time_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_time_entries_company_user'), 'time_entries', ['company_id', 'user_id'], unique=False)
    op.create_table('channel_verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('recipient_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('channel_verifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_verifications_pkey'))
    )
    op.create_table('purchase_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requester_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('details_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conversation_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('research_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_team', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reviewer_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fulfilled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("request_type::text = ANY (ARRAY['travel'::character varying, 'hotel'::character varying, 'equipment'::character varying, 'software'::character varying, 'service'::character varying, 'other'::character varying]::text[])", name=op.f('ck_purchase_request_type_valid')),
    sa.CheckConstraint("status::text = ANY (ARRAY['draft'::character varying, 'submitted'::character varying, 'under_review'::character varying, 'approved'::character varying, 'rejected'::character varying, 'fulfilled'::character varying, 'cancelled'::character varying]::text[])", name=op.f('ck_purchase_request_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_requests_pkey'))
    )
    op.create_index(op.f('ix_purchase_requests_requester_id'), 'purchase_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_purchase_requests_company_id'), 'purchase_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_pr_requester'), 'purchase_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_pr_company'), 'purchase_requests', ['company_id'], unique=False)
    # ### end Alembic commands ###
