"""baseline

Revision ID: 5a218cf8245e
Revises: 
Create Date: 2026-04-19 00:15:31.036806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a218cf8245e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_files', schema=None) as batch_op:
        batch_op.alter_column('content_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10000),
               existing_nullable=True)

    with op.batch_alter_table('expense_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_expense_document_expense_filename'), sqlite_where=sa.text('expense_id IS NOT NULL'))
        batch_op.create_unique_constraint('uq_expense_document_expense_filename', ['expense_id', 'filename'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_expense_document_expense_filename', type_='unique')
        batch_op.create_index(batch_op.f('uq_expense_document_expense_filename'), ['expense_id', 'filename'], unique=1, sqlite_where=sa.text('expense_id IS NOT NULL'))

    with op.batch_alter_table('archive_files', schema=None) as batch_op:
        batch_op.alter_column('content_text',
               existing_type=sa.String(length=10000),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
