"""content_text_to_text

Revision ID: 90bca491487a
Revises: a3a02de9babe
Create Date: 2026-04-19 10:16:04.404960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90bca491487a'
down_revision: Union[str, Sequence[str], None] = 'a3a02de9babe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_configs_company_id'), table_name='export_configs')
    op.drop_table('export_configs')
    op.drop_index(op.f('ix_expense_tags_company_id'), table_name='expense_tags')
    op.drop_table('expense_tags')
    op.alter_column('archive_files', 'content_text',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('config_versions', 'content_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('expense_attachments', 'content_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('expense_documents', 'content_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('polizas', 'content_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('setup_artifacts', 'content_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('setup_drafts', 'content_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setup_drafts', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('setup_artifacts', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('polizas', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('expense_documents', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('expense_attachments', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('config_versions', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('archive_files', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    op.create_table('expense_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('expense_tags_pkey'))
    )
    op.create_index(op.f('ix_expense_tags_company_id'), 'expense_tags', ['company_id'], unique=False)
    op.create_table('export_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_pattern', sa.VARCHAR(length=255), server_default=sa.text("'{company}_{date}_{batch_id}.csv'::character varying"), autoincrement=False, nullable=False),
    sa.Column('folder_pattern', sa.VARCHAR(length=255), server_default=sa.text("'{year}/{month}/'::character varying"), autoincrement=False, nullable=False),
    sa.Column('export_format', sa.VARCHAR(length=10), server_default=sa.text("'csv'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_format', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('export_configs_pkey'))
    )
    op.create_index(op.f('ix_export_configs_company_id'), 'export_configs', ['company_id'], unique=False)
    # ### end Alembic commands ###
